name: mast3r-slam
channels:
  - nvidia/label/cuda-12.1.0
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - setuptools=66.0.0
  - pip
  - nvidia/label/cuda-12.1.0::cuda-toolkit
  - pytorch==2.5.1=py3.12_cuda12.1_cudnn9.1.0_0
  - torchvision==0.20.1
  - gcc_linux-64=10
  - gxx_linux-64=10
  - matplotlib
  - ninja
  - absl-py 
  - tensorboard 
  - trimesh 
  - scikit-image
  - opencv 
  - einops 
  - numba 
  - gdown 
  - scikit-learn 
  - psutil 
  - av 
  - plotly
  - imageio
  - imageio-ffmpeg
  - tqdm
  - ultralytics
  - pandas
  - pyarrow
  - pip:
    - pysdf
  
